# site title
title: Yu's

# user name or organization name
user: zhangyu921

# issue repository
repository: blog

# multi-author
authors: zhangyu921

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 9#b9ef3503b1fc01364685d2c7154ddf23b415d11

# posts per page
perpage: 10


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'CREATED_AT'
